// Room icon options
export const ROOM_ICONS = [
  { id: 'home', label: 'Home', icon: 'Home' },
  { id: 'bed', label: 'Bedroom', icon: 'Bed' },
  { id: 'bed-double', label: 'Master Bedroom', icon: 'BedDouble' },
  { id: 'utensils', label: 'Kitchen', icon: 'Utensils' },
  { id: 'chef-hat', label: 'Cooking', icon: 'ChefHat' },
  { id: 'refrigerator', label: 'Pantry', icon: 'Refrigerator' },
  { id: 'bath', label: 'Bathroom', icon: 'Bath' },
  { id: 'shower-head', label: 'Shower', icon: 'ShowerHead' },
  { id: 'sofa', label: 'Living Room', icon: 'Sofa' },
  { id: 'armchair', label: 'Lounge', icon: 'Armchair' },
  { id: 'door-open', label: 'Hallway', icon: 'DoorOpen' },
  { id: 'briefcase', label: 'Office', icon: 'Briefcase' },
  { id: 'monitor', label: 'Workspace', icon: 'Monitor' },
  { id: 'library', label: 'Library', icon: 'Library' },
  { id: 'tv', label: 'Media Room', icon: 'Tv' },
  { id: 'gamepad-2', label: 'Gaming', icon: 'Gamepad2' },
  { id: 'music', label: 'Music', icon: 'Music' },
  { id: 'dumbbell', label: 'Gym', icon: 'Dumbbell' },
  { id: 'car', label: 'Garage', icon: 'Car' },
  { id: 'bike', label: 'Bike Storage', icon: 'Bike' },
  { id: 'trees', label: 'Garden', icon: 'Trees' },
  { id: 'flower', label: 'Patio', icon: 'Flower' },
  { id: 'sun', label: 'Sunroom', icon: 'Sun' },
  { id: 'warehouse', label: 'Storage', icon: 'Warehouse' },
  { id: 'box', label: 'Closet', icon: 'Box' },
  { id: 'washing-machine', label: 'Laundry', icon: 'WashingMachine' },
  { id: 'thermometer', label: 'Climate', icon: 'Thermometer' },
  { id: 'wifi', label: 'Network', icon: 'Wifi' },
  { id: 'server', label: 'Server Room', icon: 'Server' },
  { id: 'shield', label: 'Security', icon: 'Shield' },
  { id: 'zap', label: 'Utility', icon: 'Zap' },
  { id: 'baby', label: 'Nursery', icon: 'Baby' },
  { id: 'cat', label: 'Pets', icon: 'Cat' },
  { id: 'coffee', label: 'Cafe', icon: 'Coffee' },
];

// Room color palette
export const ROOM_COLORS = [
  { id: 'blue', hex: '#3b82f6', label: 'Blue' },
  { id: 'purple', hex: '#8b5cf6', label: 'Purple' },
  { id: 'pink', hex: '#ec4899', label: 'Pink' },
  { id: 'red', hex: '#ef4444', label: 'Red' },
  { id: 'orange', hex: '#f97316', label: 'Orange' },
  { id: 'yellow', hex: '#eab308', label: 'Yellow' },
  { id: 'green', hex: '#22c55e', label: 'Green' },
  { id: 'teal', hex: '#14b8a6', label: 'Teal' },
  { id: 'cyan', hex: '#06b6d4', label: 'Cyan' },
  { id: 'indigo', hex: '#6366f1', label: 'Indigo' },
  { id: 'slate', hex: '#64748b', label: 'Slate' },
  { id: 'emerald', hex: '#10b981', label: 'Emerald' },
];
