# Generated by Django 3.2.25 on 2025-12-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='ha_area_id',
            field=models.CharField(blank=True, help_text='Home Assistant Area ID for synchronization', max_length=100, null=True, unique=True),
        ),
    ]
