# Generated by Django 3.2.25 on 2025-11-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_theme_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallpaper',
            field=models.CharField(blank=True, help_text='Wallpaper ID (e.g., gradient-1) or custom image URL', max_length=255, null=True),
        ),
    ]
