# Generated by Django 3.2.25 on 2025-12-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0002_nezuroutine_routineaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='routineaction',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='routineaction',
            name='device_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
