# Generated by Django 3.2.25 on 2025-12-03 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0003_auto_20251203_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='nezuroutine',
            name='aliases',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
