# Generated by Django 3.2.25 on 2025-12-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0004_nezuroutine_aliases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nezuroutine',
            name='icon',
            field=models.CharField(default='Play', max_length=100),
        ),
        migrations.AlterField(
            model_name='routineaction',
            name='action_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scene',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
