# Generated by Django 3.2.25 on 2025-12-05 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0005_auto_20251204_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='nezuroutine',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nezuroutine',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='routineaction',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='RoutineTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('time', 'Time'), ('device_state', 'Device State'), ('sun', 'Sun Position')], max_length=20)),
                ('entity_id', models.CharField(blank=True, max_length=100, null=True)),
                ('condition', models.CharField(blank=True, max_length=20, null=True)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('days', models.CharField(default='daily', max_length=50)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='routines.nezuroutine')),
            ],
        ),
    ]
