# Generated by Django 3.2.25 on 2025-11-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('light', 'Light'), ('switch', 'Switch'), ('sensor', 'Sensor'), ('climate', 'Climate'), ('lock', 'Lock')], max_length=20)),
                ('room', models.CharField(max_length=50)),
                ('is_on', models.BooleanField(default=False)),
                ('value', models.CharField(blank=True, max_length=50, null=True)),
                ('unit', models.CharField(blank=True, max_length=10, null=True)),
                ('is_online', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
