# Generated by Django 3.2.25 on 2025-11-29 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='entity_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='device',
            name='ha_domain',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
