# Generated by Django 3.2.25 on 2025-12-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20251128_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
