# Generated by Django 3.2.25 on 2025-12-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_device_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='room',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
