# Generated by Django 3.2.25 on 2025-12-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20251204_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
