# Generated by Django 3.2.25 on 2025-12-05 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devices', '0005_device_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='room_obj',
            field=models.ForeignKey(blank=True, help_text='Room this device belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='device',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Owner of this device', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL),
        ),
    ]
