# Generated by Django 3.2.25 on 2025-12-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_auto_20251205_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_user_command',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last user-initiated command', null=True),
        ),
    ]
